name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - name: Test Version
        run: convert -version
        env:
          PATHEXT: "magick.exe"

      - name: Where is convert
        run: whereis convert


      - name: Output ENV path
        run: echo env['PATHEXT']

      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.1
      
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}


# /usr/bin/convert
# set an env variable for path to convert 
# list off stuff in that path?