name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - name: Test Version
        run: convert -version
          
      - name: Where is convert
        run: |
          whereis convert
          ls /usr/bin/convert

      - name: Output Path Before Update
        run: |
          printenv PATH
          echo "::add-path::/usr/bin/convert"
          echo "::set-env name=PATHEXT::magick"


      - name: Check Action Path After
        run: |
          printenv PATH
          printenv PATHEXT

      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.1
        run: |
          printenv PATH
          echo "::add-path::/usr/bin/convert"
          echo "::set-env name=PATHEXT::magick"
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
          PATHEXT: magick
          PATH: $PATH:/usr/bin/convert



# /usr/bin/convert
# set an env variable for path to convert 
# list off stuff in that path?