name: Build and deploy Jekyll site to GitHub Pages

# do this instead https://wiseindy.com/blog/linux/install-jekyll-on-ubuntu-16.04-windows-10/

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-16.04
    steps:
      - name: Test Version
        run: convert -version
          
      - name: Where is convert
        run: |
          whereis convert
          ls /usr/bin/convert

      - name: Output Path Before Update
        run: |
          printenv PATH
          echo "::add-path::/usr/bin/convert"
          echo "::set-env name=PATHEXT::magick"


      - name: Check Action Path After
        run: |
          printenv PATH
          printenv PATHEXT

      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@2.0.1
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}


# /usr/bin/convert
# set an env variable for path to convert 
# list off stuff in that path?